ISUCON_DB_HOST="isu3"
ISUCON_DB_PORT="3306"
ISUCON_DB_USER="isucon"
ISUCON_DB_PASSWORD="isucon"
ISUCON_DB_NAME="isuride"

ISUCON_REDIS_HOST="isu3"

# マッチング間隔（秒）
ISUCON_MATCHING_INTERVAL=0.2

WORKER_NUM=8
