# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bigdecimal'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'ulid'
gem 'redis'
gem 'rspec'
gem 'httpx'
gem 'datadog'
gem 'sinatra-sse'
